source 'https://github.com/CocoaPods/Specs.git'

ios_deployment_target = '10.0'
target 'Grocery Express' do
  platform :ios, ios_deployment_target

  # This is temporary. Remove once the pod is in the github specs repo.
  pod 'IFTTTConnectSDK', :path => './../'
end